"""Fixed-byte compatibility regression tests for the authenticated envelopes.

These tests pin the on-disk encodings of the v1 envelope
(``auth_wrap`` / ``auth_unwrap``), the v2 generation-tagged envelope
(``auth_state_wrap`` / ``auth_state_unwrap``) and the v2 state identity
(``auth_state_fingerprint``) to checked-in golden bytes under
``tests/fixtures/auth_envelope_compat/`` (see that directory's
``README.md`` for the provenance of every sample and the state it
represents).

The golden samples cover all four envelope schemes (lamport, wots,
merkle, lattice) with public deterministic test material: the legal
payload, the shared test key, both envelope versions of that payload and
the fixed v2 fingerprint. Across the four v2 samples the generations
span zero, an ordinary positive value and ``2**64 - 1``.

The golden bytes are produced once and only ever read here:

* encoding tests call the public encoding entries on the fixed inputs and
  compare the result *byte for byte* with the saved envelopes -- the
  expected bytes are never regenerated through an encoder under test;
* decoding tests start from the saved envelopes and check the scheme,
  the generation and the exact original payload, then check the fixed
  fingerprint bytes;
* version isolation, tampering boundaries, the generation floor and the
  same-generation state-identity binding are all exercised against the
  frozen samples (or in-memory mutations of them).

A missing fixture is an immediate compatibility failure: the helper
raises ``AssertionError`` instead of skipping or regenerating anything.
"""

import hashlib
import hmac
import os
import unittest

from pqattest import (
    auth_state_fingerprint,
    auth_state_unwrap,
    auth_state_wrap,
    auth_unwrap,
    auth_wrap,
)

FIXTURE_DIR = os.path.join(
    os.path.dirname(__file__), "fixtures", "auth_envelope_compat"
)

SCHEMES = ("lamport", "wots", "merkle", "lattice")

# The frozen generations (also recorded in the fixture README): zero, an
# ordinary positive value and the uint64 maximum across the four v2 samples.
GENERATIONS = {
    "lamport": 0,
    "wots": 1,
    "merkle": 2**64 - 1,
    "lattice": 0,
}
SAME_GENERATION = 7

# Documented state-identity domain separator (see auth_state_fingerprint
# docstring); used only to state the spec formula independently.
STATE_ID_DOMAIN = b"pqattest/auth-state-id/v1"

# A second fixed, public key: never used to create any golden sample, so
# every envelope must fail authentication under it.
OTHER_KEY = b"compat-other-key"

# Documented envelope header sizes: magic(8) version(1) scheme(1) then
# length(4) for v1, generation(8) + length(4) for v2; tag is 32 bytes.
V1_HEADER_BYTES = 14
V2_HEADER_BYTES = 22
TAG_BYTES = 32

SAMPLE_FILES = (
    "payload.bin",
    "envelope_v1.bin",
    "envelope_v2.bin",
    "fingerprint_v2.bin",
)


def fixture(*parts: str) -> bytes:
    """Read one frozen sample; a missing sample fails, never skips.

    A missing golden file is a compatibility failure in its own right
    (the fixed regression basis is gone), so it raises
    ``AssertionError`` instead of returning ``None`` or triggering
    regeneration.
    """
    path = os.path.join(FIXTURE_DIR, *parts)
    if not os.path.isfile(path):
        raise AssertionError(
            f"missing frozen authenticated-envelope sample: {path!s}; "
            "the golden samples must be checked in and must never be "
            "regenerated by the test suite"
        )
    with open(path, "rb") as handle:
        return handle.read()


def load_sample(scheme: str) -> dict:
    return {
        "key": fixture("key.bin"),
        "payload": fixture(scheme, "payload.bin"),
        "v1": fixture(scheme, "envelope_v1.bin"),
        "v2": fixture(scheme, "envelope_v2.bin"),
        "fingerprint": fixture(scheme, "fingerprint_v2.bin"),
    }


def load_samples() -> dict:
    return {scheme: load_sample(scheme) for scheme in SCHEMES}


def reference_identity(blob: bytes, key: bytes) -> bytes:
    """Independent spec formula for the v2 identity, not the encoder."""
    return hmac.new(key, STATE_ID_DOMAIN + blob[:-TAG_BYTES],
                    hashlib.sha256).digest()


class AuthEnvelopeCompatVectorTest(unittest.TestCase):
    def test_all_frozen_samples_are_present(self):
        self.assertTrue(os.path.isfile(os.path.join(FIXTURE_DIR, "key.bin")))
        for scheme in SCHEMES:
            for name in SAMPLE_FILES:
                with self.subTest(scheme=scheme, name=name):
                    self.assertTrue(
                        os.path.isfile(
                            os.path.join(FIXTURE_DIR, scheme, name)
                        )
                    )
        for name in ("envelope_a.bin", "envelope_b.bin",
                     "fingerprint_a.bin", "fingerprint_b.bin",
                     "payload_a.bin", "payload_b.bin"):
            self.assertTrue(
                os.path.isfile(
                    os.path.join(FIXTURE_DIR, "same_generation", name)
                )
            )
        self.assertTrue(
            os.path.isfile(os.path.join(FIXTURE_DIR, "bad_length_field.bin"))
        )

    def test_encoding_matches_frozen_envelopes_byte_for_byte(self):
        # The encoder is called on the fixed inputs and must reproduce the
        # saved bytes exactly; a mismatch here is an encoding change, not a
        # parse failure.
        for scheme, sample in load_samples().items():
            with self.subTest(scheme=scheme, version=1):
                self.assertEqual(
                    auth_wrap(
                        sample["payload"], scheme=scheme, key=sample["key"]
                    ),
                    sample["v1"],
                )
            with self.subTest(scheme=scheme, version=2):
                self.assertEqual(
                    auth_state_wrap(
                        sample["payload"],
                        scheme=scheme,
                        key=sample["key"],
                        generation=GENERATIONS[scheme],
                    ),
                    sample["v2"],
                )

    def test_frozen_envelopes_decode_to_scheme_generation_and_payload(self):
        for scheme, sample in load_samples().items():
            with self.subTest(scheme=scheme, version=1):
                got_scheme, got_payload = auth_unwrap(
                    sample["v1"], key=sample["key"]
                )
                self.assertEqual(got_scheme, scheme)
                self.assertEqual(got_payload, sample["payload"])
                self.assertIsInstance(got_payload, bytes)
            with self.subTest(scheme=scheme, version=2):
                got_scheme, got_generation, got_payload = auth_state_unwrap(
                    sample["v2"], key=sample["key"]
                )
                self.assertEqual(got_scheme, scheme)
                self.assertEqual(got_generation, GENERATIONS[scheme])
                self.assertEqual(got_payload, sample["payload"])
                self.assertIsInstance(got_payload, bytes)

    def test_frozen_v2_fingerprint_value_is_returned(self):
        for scheme, sample in load_samples().items():
            with self.subTest(scheme=scheme):
                state_id = auth_state_fingerprint(
                    sample["v2"], key=sample["key"]
                )
                # Fixed value saved on disk, never regenerated here.
                self.assertEqual(state_id, sample["fingerprint"])
                self.assertIsInstance(state_id, bytes)
                self.assertEqual(len(state_id), 32)
                # The fixed value also equals the documented spec formula
                # computed independently of the entry under test.
                self.assertEqual(
                    sample["fingerprint"],
                    reference_identity(sample["v2"], sample["key"]),
                )

    def test_same_inputs_encode_identically_on_repeated_calls(self):
        for scheme, sample in load_samples().items():
            with self.subTest(scheme=scheme):
                v1_first = auth_wrap(
                    sample["payload"], scheme=scheme, key=sample["key"]
                )
                v1_second = auth_wrap(
                    sample["payload"], scheme=scheme, key=sample["key"]
                )
                v2_first = auth_state_wrap(
                    sample["payload"],
                    scheme=scheme,
                    key=sample["key"],
                    generation=GENERATIONS[scheme],
                )
                v2_second = auth_state_wrap(
                    sample["payload"],
                    scheme=scheme,
                    key=sample["key"],
                    generation=GENERATIONS[scheme],
                )
                self.assertEqual(v1_first, v1_second)
                self.assertEqual(v2_first, v2_second)

    def test_bytes_and_bytearray_inputs_give_identical_results(self):
        for scheme, sample in load_samples().items():
            with self.subTest(scheme=scheme):
                payload, key = sample["payload"], sample["key"]
                self.assertEqual(
                    auth_wrap(payload, scheme=scheme, key=key),
                    auth_wrap(
                        bytearray(payload),
                        scheme=scheme,
                        key=bytearray(key),
                    ),
                )
                self.assertEqual(
                    auth_state_wrap(
                        payload,
                        scheme=scheme,
                        key=key,
                        generation=GENERATIONS[scheme],
                    ),
                    auth_state_wrap(
                        bytearray(payload),
                        scheme=scheme,
                        key=bytearray(key),
                        generation=GENERATIONS[scheme],
                    ),
                )
                # Decoding from bytearray gives the same fixed results and
                # still hands back plain bytes (payload and identity).
                scheme_v1, payload_v1 = auth_unwrap(
                    bytearray(sample["v1"]), key=bytearray(key)
                )
                self.assertEqual((scheme_v1, payload_v1),
                                 (scheme, payload))
                self.assertIsInstance(payload_v1, bytes)
                scheme_v2, generation_v2, payload_v2 = auth_state_unwrap(
                    bytearray(sample["v2"]), key=bytearray(key)
                )
                self.assertEqual(
                    (scheme_v2, generation_v2, payload_v2),
                    (scheme, GENERATIONS[scheme], payload),
                )
                self.assertIsInstance(payload_v2, bytes)
                identity = auth_state_fingerprint(
                    bytearray(sample["v2"]), key=bytearray(key)
                )
                self.assertEqual(identity, sample["fingerprint"])
                self.assertIsInstance(identity, bytes)


class VersionIsolationTest(unittest.TestCase):
    def test_v1_envelope_rejected_by_v2_entries(self):
        for scheme, sample in load_samples().items():
            with self.subTest(scheme=scheme, entry="auth_state_unwrap"):
                with self.assertRaises(ValueError):
                    auth_state_unwrap(sample["v1"], key=sample["key"])
            with self.subTest(scheme=scheme, entry="auth_state_fingerprint"):
                with self.assertRaises(ValueError):
                    auth_state_fingerprint(sample["v1"], key=sample["key"])

    def test_v2_envelope_rejected_by_v1_entry(self):
        for scheme, sample in load_samples().items():
            with self.subTest(scheme=scheme):
                with self.assertRaises(ValueError):
                    auth_unwrap(sample["v2"], key=sample["key"])


class EnvelopeTamperBoundaryTest(unittest.TestCase):
    def test_wrong_key_rejected(self):
        for scheme, sample in load_samples().items():
            with self.subTest(scheme=scheme, version=1):
                with self.assertRaises(ValueError):
                    auth_unwrap(sample["v1"], key=OTHER_KEY)
            with self.subTest(scheme=scheme, version=2):
                with self.assertRaises(ValueError):
                    auth_state_unwrap(sample["v2"], key=OTHER_KEY)
                with self.assertRaises(ValueError):
                    auth_state_fingerprint(sample["v2"], key=OTHER_KEY)

    def test_tag_tampering_rejected(self):
        for scheme, sample in load_samples().items():
            tampered_v1 = bytearray(sample["v1"])
            tampered_v1[-1] ^= 0x01
            tampered_v2 = bytearray(sample["v2"])
            tampered_v2[-1] ^= 0x01
            with self.subTest(scheme=scheme, version=1):
                with self.assertRaises(ValueError):
                    auth_unwrap(bytes(tampered_v1), key=sample["key"])
            with self.subTest(scheme=scheme, version=2, entry="unwrap"):
                with self.assertRaises(ValueError):
                    auth_state_unwrap(
                        bytes(tampered_v2), key=sample["key"]
                    )
            with self.subTest(scheme=scheme, version=2, entry="fingerprint"):
                with self.assertRaises(ValueError):
                    auth_state_fingerprint(
                        bytes(tampered_v2), key=sample["key"]
                    )

    def test_truncation_rejected(self):
        v1_cuts = (0, V1_HEADER_BYTES - 1, TAG_BYTES - 1,
                   V1_HEADER_BYTES + TAG_BYTES - 1)
        v2_cuts = (0, V2_HEADER_BYTES - 1, TAG_BYTES - 1, TAG_BYTES)
        for scheme, sample in load_samples().items():
            for cut in (*v1_cuts, len(sample["v1"]) - 1):
                with self.subTest(scheme=scheme, version=1, cut=cut):
                    with self.assertRaises(ValueError):
                        auth_unwrap(
                            sample["v1"][:cut], key=sample["key"]
                        )
            for cut in (*v2_cuts, len(sample["v2"]) - 1):
                with self.subTest(scheme=scheme, version=2, cut=cut):
                    with self.assertRaises(ValueError):
                        auth_state_unwrap(
                            sample["v2"][:cut], key=sample["key"]
                        )
                    with self.assertRaises(ValueError):
                        auth_state_fingerprint(
                            sample["v2"][:cut], key=sample["key"]
                        )

    def test_trailing_data_rejected(self):
        for scheme, sample in load_samples().items():
            with self.subTest(scheme=scheme, version=1):
                with self.assertRaises(ValueError):
                    auth_unwrap(
                        sample["v1"] + b"\x00", key=sample["key"]
                    )
            with self.subTest(scheme=scheme, version=2, entry="unwrap"):
                with self.assertRaises(ValueError):
                    auth_state_unwrap(
                        sample["v2"] + b"\x00", key=sample["key"]
                    )
            with self.subTest(scheme=scheme, version=2, entry="fingerprint"):
                with self.assertRaises(ValueError):
                    auth_state_fingerprint(
                        sample["v2"] + b"\x00", key=sample["key"]
                    )

    def test_expect_mismatch_rejected_and_match_accepted(self):
        for scheme, sample in load_samples().items():
            other = tuple(name for name in SCHEMES if name != scheme)
            with self.subTest(scheme=scheme, version=1):
                self.assertEqual(
                    auth_unwrap(
                        sample["v1"], key=sample["key"], expect=scheme
                    )[0],
                    scheme,
                )
                for wrong in other:
                    with self.subTest(wrong=wrong):
                        with self.assertRaises(ValueError):
                            auth_unwrap(
                                sample["v1"],
                                key=sample["key"],
                                expect=wrong,
                            )
            with self.subTest(scheme=scheme, version=2):
                self.assertEqual(
                    auth_state_unwrap(
                        sample["v2"], key=sample["key"], expect=scheme
                    )[0],
                    scheme,
                )
                for wrong in other:
                    with self.subTest(wrong=wrong):
                        with self.assertRaises(ValueError):
                            auth_state_unwrap(
                                sample["v2"],
                                key=sample["key"],
                                expect=wrong,
                            )

    def test_correct_tag_but_wrong_length_field_is_structurally_rejected(self):
        key = fixture("key.bin")
        blob = fixture("bad_length_field.bin")
        # The fixture carries a valid tag over its tampered body, so the
        # rejection must come from the length-field structure check, not
        # the authentication layer.
        self.assertTrue(
            hmac.compare_digest(
                hmac.new(key, blob[:-TAG_BYTES], hashlib.sha256).digest(),
                blob[-TAG_BYTES:],
            )
        )
        with self.assertRaises(ValueError):
            auth_state_unwrap(blob, key=key)
        with self.assertRaises(ValueError):
            auth_state_fingerprint(blob, key=key)


class GenerationFloorTest(unittest.TestCase):
    def test_generation_equal_to_floor_accepted(self):
        for scheme, sample in load_samples().items():
            with self.subTest(scheme=scheme):
                got_scheme, got_generation, got_payload = auth_state_unwrap(
                    sample["v2"],
                    key=sample["key"],
                    min_generation=GENERATIONS[scheme],
                )
                self.assertEqual(
                    (got_scheme, got_generation, got_payload),
                    (scheme, GENERATIONS[scheme], sample["payload"]),
                )

    def test_generation_below_floor_rejected(self):
        # gen 0 (lamport) against floor 1, and gen 1 (wots) against floor 2;
        # the 2**64-1 merkle sample cannot be paired with a higher legal
        # floor and is covered at equality instead.
        for scheme in ("lamport", "wots", "lattice"):
            sample = load_sample(scheme)
            floor = GENERATIONS[scheme] + 1
            with self.subTest(scheme=scheme, floor=floor):
                with self.assertRaises(ValueError):
                    auth_state_unwrap(
                        sample["v2"],
                        key=sample["key"],
                        min_generation=floor,
                    )

    def test_max_uint64_generation_decodes_and_accepts_equal_floor(self):
        sample = load_sample("merkle")
        self.assertEqual(GENERATIONS["merkle"], 2**64 - 1)
        _, generation, _ = auth_state_unwrap(
            sample["v2"], key=sample["key"], min_generation=2**64 - 1
        )
        self.assertEqual(generation, 2**64 - 1)


class SameGenerationStateBindingTest(unittest.TestCase):
    """Two different legal envelopes at one generation (frozen pair)."""

    def setUp(self):
        self.key = fixture("key.bin")
        self.env_a = fixture("same_generation", "envelope_a.bin")
        self.env_b = fixture("same_generation", "envelope_b.bin")
        self.payload_a = fixture("same_generation", "payload_a.bin")
        self.payload_b = fixture("same_generation", "payload_b.bin")
        self.fp_a = fixture("same_generation", "fingerprint_a.bin")
        self.fp_b = fixture("same_generation", "fingerprint_b.bin")

    def test_each_envelope_decodes_independently(self):
        scheme_a, generation_a, payload_a = auth_state_unwrap(
            self.env_a, key=self.key
        )
        scheme_b, generation_b, payload_b = auth_state_unwrap(
            self.env_b, key=self.key
        )
        self.assertEqual((scheme_a, generation_a), ("lamport", SAME_GENERATION))
        self.assertEqual((scheme_b, generation_b), ("lamport", SAME_GENERATION))
        self.assertEqual(payload_a, self.payload_a)
        self.assertEqual(payload_b, self.payload_b)
        # Genuinely different states at the same generation: distinct
        # payloads and therefore distinct fixed fingerprints.
        self.assertNotEqual(payload_a, payload_b)
        self.assertNotEqual(self.fp_a, self.fp_b)
        self.assertEqual(
            auth_state_fingerprint(self.env_a, key=self.key), self.fp_a
        )
        self.assertEqual(
            auth_state_fingerprint(self.env_b, key=self.key), self.fp_b
        )

    def test_other_envelope_fingerprint_rejected(self):
        with self.assertRaises(ValueError):
            auth_state_unwrap(
                self.env_a,
                key=self.key,
                min_generation=SAME_GENERATION,
                expect_state_id=self.fp_b,
            )
        with self.assertRaises(ValueError):
            auth_state_unwrap(
                self.env_b,
                key=self.key,
                min_generation=SAME_GENERATION,
                expect_state_id=self.fp_a,
            )

    def test_own_fingerprint_accepts_including_repeated_submission(self):
        # An exact replay of an already accepted envelope remains accepted,
        # including every time it is resubmitted with its saved identity.
        for _ in range(3):
            scheme_a, generation_a, payload_a = auth_state_unwrap(
                self.env_a,
                key=self.key,
                min_generation=SAME_GENERATION,
                expect_state_id=self.fp_a,
            )
            self.assertEqual(
                (scheme_a, generation_a), ("lamport", SAME_GENERATION)
            )
            self.assertEqual(payload_a, self.payload_a)
        scheme_b, generation_b, payload_b = auth_state_unwrap(
            self.env_b,
            key=self.key,
            min_generation=SAME_GENERATION,
            expect_state_id=self.fp_b,
        )
        self.assertEqual((scheme_b, generation_b, payload_b),
                         ("lamport", SAME_GENERATION, self.payload_b))

    def test_floor_still_applies_alongside_identity(self):
        for envelope, state_id in ((self.env_a, self.fp_a),
                                   (self.env_b, self.fp_b)):
            with self.subTest():
                with self.assertRaises(ValueError):
                    auth_state_unwrap(
                        envelope,
                        key=self.key,
                        min_generation=SAME_GENERATION + 1,
                        expect_state_id=state_id,
                    )


class NonBytesInputTypeTest(unittest.TestCase):
    def setUp(self):
        sample = load_sample("lamport")
        self.key = sample["key"]
        self.payload = sample["payload"]
        self.v1 = sample["v1"]
        self.v2 = sample["v2"]
        self.bad_values = (None, 42, 4.5, "bytes-like", [0], (0,), object())

    def test_decode_entries_reject_non_bytes_data(self):
        for bad in self.bad_values:
            with self.subTest(entry="auth_unwrap", bad=type(bad).__name__):
                with self.assertRaises(TypeError):
                    auth_unwrap(bad, key=self.key)
            with self.subTest(entry="auth_state_unwrap",
                              bad=type(bad).__name__):
                with self.assertRaises(TypeError):
                    auth_state_unwrap(bad, key=self.key)
            with self.subTest(entry="auth_state_fingerprint",
                              bad=type(bad).__name__):
                with self.assertRaises(TypeError):
                    auth_state_fingerprint(bad, key=self.key)

    def test_encode_entries_reject_non_bytes_payload(self):
        for bad in self.bad_values:
            with self.subTest(entry="auth_wrap", bad=type(bad).__name__):
                with self.assertRaises(TypeError):
                    auth_wrap(bad, scheme="lamport", key=self.key)
            with self.subTest(entry="auth_state_wrap",
                              bad=type(bad).__name__):
                with self.assertRaises(TypeError):
                    auth_state_wrap(
                        bad,
                        scheme="lamport",
                        key=self.key,
                        generation=0,
                    )

    def test_all_entries_reject_non_bytes_key(self):
        for bad in self.bad_values:
            with self.subTest(entry="auth_wrap", bad=type(bad).__name__):
                with self.assertRaises(TypeError):
                    auth_wrap(self.payload, scheme="lamport", key=bad)
            with self.subTest(entry="auth_unwrap", bad=type(bad).__name__):
                with self.assertRaises(TypeError):
                    auth_unwrap(self.v1, key=bad)
            with self.subTest(entry="auth_state_wrap",
                              bad=type(bad).__name__):
                with self.assertRaises(TypeError):
                    auth_state_wrap(
                        self.payload,
                        scheme="lamport",
                        key=bad,
                        generation=0,
                    )
            with self.subTest(entry="auth_state_unwrap",
                              bad=type(bad).__name__):
                with self.assertRaises(TypeError):
                    auth_state_unwrap(self.v2, key=bad)
            with self.subTest(entry="auth_state_fingerprint",
                              bad=type(bad).__name__):
                with self.assertRaises(TypeError):
                    auth_state_fingerprint(self.v2, key=bad)


if __name__ == "__main__":
    unittest.main()
