"""Fixed-byte compatibility regression tests for the toy lattice path.

These tests pin the on-wire v1 encodings of the teaching-only toy
lattice key pair and signatures to checked-in golden bytes (see
``tests/fixtures/toy_lattice_compat/README.md``). The golden samples
were produced once from documented, public deterministic inputs and
are only ever read here: they are never regenerated by writing the
output of the functions under test back as the expected value, and the
assertions are byte-for-byte comparisons against the samples rather
than length checks or current-version round trips.

Coverage:

* a key pair generated through the public ``toy_lattice_keygen`` entry
  from the fixed eight-byte key input encodes byte-for-byte to the
  frozen private/public samples, and keys restored *only* from those
  samples are value-equal;
* signing through the public ``toy_lattice_sign`` entry with the fixed
  eight-byte signing randomness and fixed message encodes to the frozen
  context-free signature, and a signature restored only from the
  sample verifies the original message; the private key restored only
  from its sample re-produces that exact signature under the same
  inputs;
* omitting ``context`` and passing ``None``, ``b""``, ``bytearray()``
  or ``""`` all give the frozen context-free bytes;
* the fixed non-empty Chinese context gives a second frozen signature
  whether expressed as ``str``, UTF-8 ``bytes`` or ``bytearray``, and
  the message's ``str``/``bytes``/``bytearray`` forms give the same
  result;
* the correct combination returns ``True`` while a changed message,
  public key, signature tag or context returns ``False``, and
  context-free and context-bound signatures never cross-verify;
* all three decode entries accept ``bytes`` and ``bytearray``
  equivalently, reject every other input type with ``TypeError``, and
  reject bad magic, unknown version, truncation, trailing bytes and
  out-of-range ``E`` coefficients with ``ValueError``; coefficient 256
  stays a legal decoded value even though keygen only draws single
  bytes;
* a structurally valid signature whose tag was altered decodes but
  verifies ``False``; wrong public-key or context types at verification
  raise ``TypeError``.
"""

import os
import unittest

from pqattest import (
    ToyLatticePrivateKey,
    ToyLatticePublicKey,
    ToyLatticeSignature,
    toy_lattice_keygen,
    toy_lattice_sign,
    toy_lattice_verify,
)

FIXTURE_DIR = os.path.join(os.path.dirname(__file__), "fixtures", "toy_lattice_compat")

# Documented deterministic public inputs (see the fixture README):
# fixed eight-byte key input, two fixed eight-byte signing randomness
# inputs, one fixed ASCII message, one fixed non-empty Chinese context
# and one fixed message that was never signed.
KEY_INPUT = b"lat-key1"
SIGN_INPUT_NOCTX = b"lat-sig1"
SIGN_INPUT_CTX = b"lat-ctx1"
MESSAGE = b"compat-toy-lattice-v1"
MESSAGE_TAMPERED = b"compat-toy-lattice-v1-changed"
CONTEXT = "教学格基玩具签名"
CONTEXT_BYTES = CONTEXT.encode("utf-8")

SAMPLE_NAMES = (
    "private_key.bin",
    "public_key.bin",
    "signature_noctx.bin",
    "signature_ctx_zh.bin",
)

# Documented v1 codec layout (see the to_bytes docstrings and README):
# 8 magic | 1 version | 16 E field for keys (25 bytes total).
_KEY_FIELD_OFFSET = 9
# Signatures: 8 magic | 1 version | 16 E | 4 tag length | 32 tag.
_SIGNATURE_TAG_LENGTH_OFFSET = 25
_SIGNATURE_TAG_OFFSET = 29


def fixed_tokens(value: bytes):
    def token_bytes(size: int) -> bytes:
        assert size == len(value)
        return value

    return token_bytes


def fixture(name: str) -> bytes:
    """Read one frozen sample; a missing sample fails, never skips.

    A missing golden file is a compatibility failure in its own right
    (the fixed regression basis is gone), so it raises
    ``AssertionError`` instead of returning ``None`` or triggering
    regeneration.
    """
    path = os.path.join(FIXTURE_DIR, name)
    if not os.path.isfile(path):
        raise AssertionError(
            f"missing frozen toy lattice compatibility sample: {path!s}; "
            "the golden samples must be checked in and must never be "
            "regenerated by the test suite"
        )
    with open(path, "rb") as handle:
        return handle.read()


def load_samples() -> dict:
    return {name[:-4]: fixture(name) for name in SAMPLE_NAMES}


class ToyLatticeCompatVectorTest(unittest.TestCase):
    def test_all_frozen_samples_are_present(self):
        for name in SAMPLE_NAMES:
            with self.subTest(name=name):
                self.assertTrue(
                    os.path.isfile(os.path.join(FIXTURE_DIR, name))
                )

    def test_keygen_matches_frozen_key_samples_byte_for_byte(self):
        samples = load_samples()
        private_key, public_key = toy_lattice_keygen(
            token_bytes=fixed_tokens(KEY_INPUT)
        )
        # The public entry over the documented fixed input must match
        # the frozen bytes exactly: any difference is an encoding or
        # key-derivation change, not a parse failure.
        self.assertEqual(private_key.to_bytes(), samples["private_key"])
        self.assertEqual(public_key.to_bytes(), samples["public_key"])

    def test_samples_decode_to_value_equal_keys(self):
        samples = load_samples()
        generated_private, generated_public = toy_lattice_keygen(
            token_bytes=fixed_tokens(KEY_INPUT)
        )
        # Restoration uses only the frozen sample bytes.
        restored_private = ToyLatticePrivateKey.from_bytes(samples["private_key"])
        restored_public = ToyLatticePublicKey.from_bytes(samples["public_key"])
        self.assertEqual(restored_private, generated_private)
        self.assertEqual(restored_public, generated_public)
        # The toy key pair shares one vector by design.
        self.assertEqual(restored_private.s, restored_public.t)

    def test_sign_matches_frozen_context_free_sample_byte_for_byte(self):
        samples = load_samples()
        private_key, _ = toy_lattice_keygen(token_bytes=fixed_tokens(KEY_INPUT))
        signature = toy_lattice_sign(
            MESSAGE, private_key, token_bytes=fixed_tokens(SIGN_INPUT_NOCTX)
        )
        self.assertEqual(signature.to_bytes(), samples["signature_noctx"])

    def test_restored_samples_verify_and_restored_private_resigns_same_bytes(self):
        samples = load_samples()
        # Every object below comes only from the frozen samples.
        private_key = ToyLatticePrivateKey.from_bytes(samples["private_key"])
        public_key = ToyLatticePublicKey.from_bytes(samples["public_key"])
        signature = ToyLatticeSignature.from_bytes(samples["signature_noctx"])
        self.assertTrue(toy_lattice_verify(MESSAGE, signature, public_key))
        # The restored private key re-signs to the exact frozen bytes
        # under the documented fixed randomness and message.
        resigned = toy_lattice_sign(
            MESSAGE, private_key, token_bytes=fixed_tokens(SIGN_INPUT_NOCTX)
        )
        self.assertEqual(resigned.to_bytes(), samples["signature_noctx"])
        self.assertEqual(resigned, signature)


class ToyLatticeCompatContextTest(unittest.TestCase):
    def _key(self):
        private_key, public_key = toy_lattice_keygen(
            token_bytes=fixed_tokens(KEY_INPUT)
        )
        return private_key, public_key

    def test_omitted_none_and_three_empty_contexts_are_identical(self):
        samples = load_samples()
        private_key, _ = self._key()
        variants = {
            "omitted": {},
            "none": {"context": None},
            "empty_bytes": {"context": b""},
            "empty_bytearray": {"context": bytearray()},
            "empty_str": {"context": ""},
        }
        for name, kwargs in variants.items():
            with self.subTest(variant=name):
                signature = toy_lattice_sign(
                    MESSAGE,
                    private_key,
                    token_bytes=fixed_tokens(SIGN_INPUT_NOCTX),
                    **kwargs,
                )
                self.assertEqual(
                    signature.to_bytes(), samples["signature_noctx"]
                )

    def test_chinese_context_forms_match_frozen_sample(self):
        samples = load_samples()
        private_key, public_key = self._key()
        context_forms = {
            "str": CONTEXT,
            "utf8_bytes": CONTEXT_BYTES,
            "utf8_bytearray": bytearray(CONTEXT_BYTES),
        }
        for ctx_name, context in context_forms.items():
            with self.subTest(context=ctx_name):
                signature = toy_lattice_sign(
                    MESSAGE,
                    private_key,
                    token_bytes=fixed_tokens(SIGN_INPUT_CTX),
                    context=context,
                )
                # Signing output is pinned to the frozen bytes, not to
                # a freshly generated value.
                self.assertEqual(
                    signature.to_bytes(), samples["signature_ctx_zh"]
                )
                # The message's str/UTF-8 bytes/bytearray forms verify
                # equivalently against the restored frozen signature.
                restored = ToyLatticeSignature.from_bytes(
                    samples["signature_ctx_zh"]
                )
                for msg_name, message in (
                    ("bytes", MESSAGE),
                    ("str", MESSAGE.decode("ascii")),
                    ("bytearray", bytearray(MESSAGE)),
                ):
                    with self.subTest(context=ctx_name, message=msg_name):
                        self.assertTrue(
                            toy_lattice_verify(
                                message, restored, public_key, context=context
                            )
                        )

    def test_context_and_no_context_signatures_do_not_cross_verify(self):
        samples = load_samples()
        _, public_key = self._key()
        noctx = ToyLatticeSignature.from_bytes(samples["signature_noctx"])
        bound = ToyLatticeSignature.from_bytes(samples["signature_ctx_zh"])
        # Correct combinations verify.
        self.assertTrue(toy_lattice_verify(MESSAGE, noctx, public_key))
        self.assertTrue(
            toy_lattice_verify(MESSAGE, bound, public_key, context=CONTEXT)
        )
        # Context-free signature fails whenever a context is supplied.
        self.assertFalse(
            toy_lattice_verify(MESSAGE, noctx, public_key, context=CONTEXT)
        )
        # Context-bound signature fails without a context or under a
        # different context.
        self.assertFalse(toy_lattice_verify(MESSAGE, bound, public_key))
        self.assertFalse(
            toy_lattice_verify(MESSAGE, bound, public_key, context="other/v1")
        )


class ToyLatticeCompatVerificationMatrixTest(unittest.TestCase):
    def setUp(self):
        samples = load_samples()
        self.private_key = ToyLatticePrivateKey.from_bytes(samples["private_key"])
        self.public_key = ToyLatticePublicKey.from_bytes(samples["public_key"])
        self.signature = ToyLatticeSignature.from_bytes(
            samples["signature_noctx"]
        )
        self.bound = ToyLatticeSignature.from_bytes(
            samples["signature_ctx_zh"]
        )
        # A different fixed public key generated from a distinct fixed
        # eight-byte input (negative control only, not a golden value).
        _, self.other_public = toy_lattice_keygen(
            token_bytes=fixed_tokens(b"otrk-in!")
        )

    def test_correct_combination_is_true(self):
        self.assertTrue(
            toy_lattice_verify(MESSAGE, self.signature, self.public_key)
        )

    def test_changed_message_is_false(self):
        self.assertFalse(
            toy_lattice_verify(
                MESSAGE_TAMPERED, self.signature, self.public_key
            )
        )
        self.assertNotEqual(MESSAGE, MESSAGE_TAMPERED)

    def test_changed_public_key_is_false(self):
        self.assertFalse(
            toy_lattice_verify(MESSAGE, self.signature, self.other_public)
        )

    def test_changed_signature_tag_is_false(self):
        wrong_tag = ToyLatticeSignature(
            self.signature.u, b"\x00" * 31 + bytes((self.signature.tag[-1] ^ 0x01,))
        )
        self.assertFalse(
            toy_lattice_verify(MESSAGE, wrong_tag, self.public_key)
        )

    def test_changed_random_vector_is_false(self):
        wrong_u = ToyLatticeSignature(b"\x00" * 16, self.signature.tag)
        self.assertFalse(
            toy_lattice_verify(MESSAGE, wrong_u, self.public_key)
        )

    def test_changed_context_is_false(self):
        self.assertFalse(
            toy_lattice_verify(
                MESSAGE, self.bound, self.public_key, context="enroll/v9"
            )
        )

    def test_wrong_public_key_type_raises_type_error(self):
        for bad in (None, self.public_key.to_bytes(), self.private_key, object()):
            with self.subTest(bad=bad):
                with self.assertRaises(TypeError):
                    toy_lattice_verify(MESSAGE, self.signature, bad)

    def test_wrong_context_type_raises_type_error(self):
        # bytes/bytearray/str/None are all legal; these are not.
        for bad in (123, [CONTEXT], object(), True):
            with self.subTest(bad=type(bad).__name__):
                with self.assertRaises(TypeError):
                    toy_lattice_verify(
                        MESSAGE, self.signature, self.public_key, context=bad
                    )
                with self.assertRaises(TypeError):
                    toy_lattice_verify(
                        MESSAGE, self.bound, self.public_key, context=bad
                    )


class ToyLatticeCompatParsingBoundaryTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.samples = load_samples()

    def decode_entries(self):
        """Every decode entry in scope, paired with its frozen sample."""
        return (
            (
                "private_key",
                ToyLatticePrivateKey.from_bytes,
                self.samples["private_key"],
            ),
            (
                "public_key",
                ToyLatticePublicKey.from_bytes,
                self.samples["public_key"],
            ),
            (
                "signature",
                ToyLatticeSignature.from_bytes,
                self.samples["signature_noctx"],
            ),
        )

    def test_bytes_and_bytearray_restore_equal_objects(self):
        for name, from_bytes, raw in self.decode_entries():
            with self.subTest(entry=name):
                from_bytes_value = from_bytes(raw)
                from_array = from_bytes(bytearray(raw))
                self.assertEqual(from_array, from_bytes_value)
                self.assertEqual(hash(from_array), hash(from_bytes_value))

    def test_non_bytes_inputs_raise_type_error(self):
        for name, from_bytes, raw in self.decode_entries():
            bad_inputs = (
                ("str", raw.decode("latin-1")),
                ("none", None),
                ("int", 42),
                ("list", [raw]),
                ("memoryview", memoryview(raw)),
            )
            for label, bad in bad_inputs:
                with self.subTest(entry=name, bad=label):
                    with self.assertRaises(TypeError):
                        from_bytes(bad)

    def test_bad_magic_raises_value_error(self):
        for name, from_bytes, raw in self.decode_entries():
            bad = bytearray(raw)
            bad[0] ^= 0x01
            with self.subTest(entry=name):
                with self.assertRaises(ValueError):
                    from_bytes(bytes(bad))

    def test_unknown_version_raises_value_error(self):
        for name, from_bytes, raw in self.decode_entries():
            bad = raw[:8] + bytes((2,)) + raw[9:]
            with self.subTest(entry=name):
                with self.assertRaises(ValueError):
                    from_bytes(bad)

    def test_truncation_raises_value_error(self):
        for name, from_bytes, raw in self.decode_entries():
            for case, blob in (
                ("empty", b""),
                ("cut_in_magic", raw[:7]),
                ("cut_before_field", raw[:8]),
                ("short_by_one", raw[:-1]),
            ):
                with self.subTest(entry=name, case=case):
                    with self.assertRaises(ValueError):
                        from_bytes(blob)

    def test_trailing_bytes_raise_value_error(self):
        for name, from_bytes, raw in self.decode_entries():
            with self.subTest(entry=name):
                with self.assertRaises(ValueError):
                    from_bytes(raw + b"\x00")

    def test_coefficient_above_256_raises_value_error(self):
        # 0x0101 == 257 must be rejected even though it fits two bytes.
        for name, from_bytes, raw in self.decode_entries():
            bad = (
                raw[:_KEY_FIELD_OFFSET]
                + b"\x01\x01"
                + raw[_KEY_FIELD_OFFSET + 2 :]
            )
            with self.subTest(entry=name):
                with self.assertRaises(ValueError):
                    from_bytes(bad)

    def test_coefficient_256_is_accepted_on_decode(self):
        # Keygen only draws single-byte coefficients, but the decode
        # range must stay 0..256: a structurally valid encoding whose
        # first E coefficient is 256 parses for every entry.
        for name, from_bytes, raw in self.decode_entries():
            blob = (
                raw[:_KEY_FIELD_OFFSET]
                + b"\x01\x00"
                + raw[_KEY_FIELD_OFFSET + 2 :]
            )
            with self.subTest(entry=name):
                restored = from_bytes(blob)
                field_name = {"private_key": "s", "public_key": "t", "signature": "u"}[
                    name
                ]
                field = getattr(restored, field_name)
                self.assertEqual(int.from_bytes(field[:2], "big"), 256)

    def test_signature_tag_length_other_than_32_raises_value_error(self):
        raw = self.samples["signature_noctx"]
        header = raw[:_SIGNATURE_TAG_LENGTH_OFFSET]
        tail = raw[_SIGNATURE_TAG_OFFSET:]
        for length in (0, 1, 31, 33, 64):
            blob = header + length.to_bytes(4, "big") + b"\x00" * length
            with self.subTest(length=length):
                with self.assertRaises(ValueError):
                    ToyLatticeSignature.from_bytes(blob)
        # A length that says 32 but whose body is short must fail too.
        short = header + (32).to_bytes(4, "big") + tail[:-1]
        with self.assertRaises(ValueError):
            ToyLatticeSignature.from_bytes(short)

    def test_structurally_valid_signature_with_altered_tag_decodes_but_fails(self):
        raw = bytearray(self.samples["signature_noctx"])
        raw[-1] ^= 0x01
        tampered = bytes(raw)
        # Decoding succeeds: the tag is still exactly 32 bytes.
        signature = ToyLatticeSignature.from_bytes(tampered)
        public_key = ToyLatticePublicKey.from_bytes(self.samples["public_key"])
        self.assertEqual(len(signature.tag), 32)
        # Verification of the original message is False, not an error.
        self.assertFalse(toy_lattice_verify(MESSAGE, signature, public_key))


if __name__ == "__main__":
    unittest.main()
